### ISSUE TITLE
Input history wiped when sending input through triggers

### ISSUE THREAD

**Issue by jhall11** [mudpuppy-rs/mudpuppy#61]
I haven't narrowed down exactly what is happening, but what I notice is while not in combat and sending commands I can scroll through my command history in the input prompt. When in combat, with triggers firing, I can at most scroll up one command but usually the input prompt is empty when going up in the history.

**Comment by cpu** [comment]
Thanks for the report! This was a side-effect of the clumsy way I implemented https://github.com/mudpuppy-rs/mudpuppy/issues/12 that will be fixed with https://github.com/mudpuppy-rs/mudpuppy/pull/64.
